### ISSUE TITLE
The error occurs when training an AE with Cityscapes.

### ISSUE THREAD

**Issue by cpy0029** [nku-zhichengzhang/ExtDM#3]
Original Traceback (most recent call last):
  File "/home/data/anaconda3/envs/mambavp/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker

    output = module(*input, **kwargs)

  File "/home/data/anaconda3/envs/mambavp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl

    return self._call_impl(*args, **kwargs)

  File "/home/data/anaconda3/envs/mambavp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl

    return forward_call(*args, **kwargs)

  File "/home/data/code/ExtDM/model/LFAE/model.py", line 165, in forward

    source_region_params = self.region_predictor(x['source'])

  File "/home/data/anaconda3/envs/mambavp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl

    return self._call_impl(*args, **kwargs)

  File "/home/data/anaconda3/envs/mambavp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl

    return forward_call(*args, **kwargs)

  File "/home/data/code/ExtDM/model/LFAE/region_predictor.py", line 81, in forward

    feature_map = self.predictor(x)

  File "/home/data/anaconda3/envs/mambavp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl

    return self._call_impl(*args, **kwargs)

  File "/home/data/anaconda3/envs/mambavp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl

    return forward_call(*args, **kwargs)

  File "/home/data/code/ExtDM/model/LFAE/util.py", line 214, in forward

    return self.decoder(self.encoder(x))

  File "/home/data/anaconda3/envs/mambavp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl

    return self._call_impl(*args, **kwargs)

  File "/home/data/anaconda3/envs/mambavp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl

    return forward_call(*args, **kwargs)

  File "/home/data/code/ExtDM/model/LFAE/util.py", line 171, in forward

    outs.append(down_block(outs[-1]))

  File "/home/data/anaconda3/envs/mambavp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl

    return self._call_impl(*args, **kwargs)

  File "/home/data/anaconda3/envs/mambavp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl

    return forward_call(*args, **kwargs)

  File "/home/data/code/ExtDM/model/LFAE/util.py", line 131, in forward

    out = self.pool(out)

  File "/home/data/anaconda3/envs/mambavp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl

    return self._call_impl(*args, **kwargs)

  File "/home/data/anaconda3/envs/mambavp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl

    return forward_call(*args, **kwargs)

  File "/home/data/anaconda3/envs/mambavp/lib/python3.10/site-packages/torch/nn/modules/pooling.py", line 635, in forward

    return F.avg_pool2d(input, self.kernel_size, self.stride,

RuntimeError: Given input size: (1024x1x1). Calculated output size: (1024x0x0). Output size is too small

**Comment by nku-zhichengzhang** [comment]
Thank you for reporting this issue. I haven't personally encountered this specific error, but I can offer some insights and recommendations.

The error message suggests that there's a problem with the dimensions of your input tensor when it reaches the average pooling layer. Specifically, it seems that the spatial dimensions (height and width) have become too small (1x1) for further pooling, resulting in an invalid output size of 0x0.

This could be caused by a mismatch between your input image size and the network architecture, particularly if you've modified the default configuration.

Here are some suggestions:

1. Use the default configuration: I strongly recommend using the default configuration provided with the model. The default settings have been tested and should work correctly with the Cityscapes dataset.

2. Check your input dimensions: Ensure that your input images from the Cityscapes dataset are of the expected size. If you're preprocessing the images, make sure you're not inadvertently reducing their size too much.

3. Review any custom changes: If you've made any modifications to the model architecture or hyperparameters, carefully review these changes. They might be causing the tensor to be reduced too much before reaching the problematic pooling layer.

4. Print intermediate tensor shapes: You could add print statements to log the shape of the tensor at various stages of the forward pass. This might help identify where exactly the tensor is being reduced to a 1x1 spatial dimension.

If the issue persists even with the default configuration and correct input sizes, please provide more details about your setup.
- Any modifications you've made to the default configuration
- The dimensions of your input images
This additional information will help in further diagnosing the problem.
